### ISSUE TITLE
ModuleNotFoundError: No module named 'adamsa'

### ISSUE THREAD

**Issue by KittyTechnoProgrammer** [mxmssh/manul#44]
This error appears when trying to use radamsa

Probably an easy fix but still wanted to report it. 

Traceback (most recent call last):
  File "./manul.py", line 557, in init_mutators
    self.user_mutators[module_name] = importlib.import_module(module_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'adamsa'

**Comment by KittyTechnoProgrammer** [comment]
issue is in

def init_mutators(self):
        INFO(0, bcolors.BOLD + bcolors.HEADER, self.log_file, "Initializing mutators")

        for module_name in self.mutator_weights:
            if "afl" == module_name or "radamsa" == module_name:
                continue
            try:
                self.user_mutators[module_name] = importlib.import_module(module_name)
            except ImportError as exc:
                ERROR("Unable to load user provided mutator %s. %s" % (module_name, exc.message))

            self.user_mutators[module_name].init()

**Comment by KittyTechnoProgrammer** [comment]
I found the solution.
I had a typo in my manul.config file instead of radamsa:2 I had adamsa:2

Suggest : Put a note to the user to check the config when this error occurs
